#!/bin/bash
exec 2>&1

if [ ! -p /tmp/json_pipe ] ; then
  if [ -f /tmp/json_pipe ] ; then
    rm -f /tmp/json_pipe
  fi
  mkfifo /tmp/json_pipe
fi

exec /usr/bin/websocketd --staticdir=/var/www/meas --port=8080 cat /tmp/json_pipe
