#!/bin/bash

. /home/rhizomatica/bin/vars.sh

/sbin/iptables -t nat -vnL | egrep "MASQUERADE.*all.*$_PUBIF.*172.16.0.0/16.*0.0.0.0/0"
if [ $? != 0 ] ; then
	# Add the Masquerade RULE
	iptables -t nat -I POSTROUTING -s 172.16.0.0/16 -o $_PUBIF -j MASQUERADE
fi
